### ISSUE TITLE
Trocar a label Bem Vindo ao Site Scan

### ISSUE THREAD

**Issue by ItamarAlves** [Off-Tools/site-scan#22]
Trocar a label dá página Bem Vindo ao Site Scan, para Bem Vindo ao OFF-Tools.
![home](https://user-images.githubusercontent.com/47131680/106037870-9c21c680-60ad-11eb-922f-2cf001aa1db4.png)

**Comment by carlosadrianosj** [comment]
ja fiz isso, coloquei OFF Tools: Site Scan

**Comment by ItamarAlves** [comment]
opa show, mas o que acha de só apenas OFF Tools?

Por que essa página não seria tipo, onde vai estar todas as ferramentas da OFF Tools no caso, ae o Site Scan estaria na seção de Ferramentas no caso.. 
o que acha dessa idéia?

**Comment by carlosadrianosj** [comment]
Opa, concordo contigo, creio o que esse site vai estar todas as nossas ferramentas relacionadas a web, seria uma boa mesmo colocar do jeito que vc falou

**Comment by ItamarAlves** [comment]
Opa beleza, vou prosseguir com a alteração.
